import os
import shutil
import sys
from pathlib import Path


# Where the macOS app keeps the files it reads and writes, see install_mac_app_data()
MAC_APP_DATA_DIR = os.path.expanduser("~/Library/Application Support/AutoSplit64++")


def install_mac_app_data():
    """
    A macOS .app can be installed anywhere and must not modify itself. Copy the files bundled
    in it to MAC_APP_DATA_DIR, next to the user's settings, and run from there.
    """
    def copy_if_changed(src, dst):
        if not os.path.exists(dst) or os.path.getsize(src) != os.path.getsize(dst) or os.path.getmtime(src) != os.path.getmtime(dst):
            shutil.copy2(src, dst)

    def copy_if_missing(src, dst):
        if not os.path.exists(dst):
            shutil.copy2(src, dst)

    bundle = sys._MEIPASS
    os.makedirs(MAC_APP_DATA_DIR, exist_ok=True)
    # Updated with the app
    for name in ("logic", "resources"):
        shutil.copytree(os.path.join(bundle, name), os.path.join(MAC_APP_DATA_DIR, name), dirs_exist_ok=True, copy_function=copy_if_changed)
    copy_if_changed(os.path.join(bundle, "defaults.ini"), os.path.join(MAC_APP_DATA_DIR, "defaults.ini"))
    # Edited or generated by the user, so existing files are kept
    for name in ("routes", "templates"):
        shutil.copytree(os.path.join(bundle, name), os.path.join(MAC_APP_DATA_DIR, name), dirs_exist_ok=True, copy_function=copy_if_missing)

    os.chdir(MAC_APP_DATA_DIR)


def base_path(relative_path=None):
    directory = os.path.dirname(sys.argv[0])
    if getattr(sys, "frozen", False) and sys.platform == "darwin":
        directory = MAC_APP_DATA_DIR

    if not relative_path:
        return directory
    else:
        return os.path.join(directory, relative_path).replace('\\', '/')


def absolute_path(relative_path=None):
    if not relative_path:
        return str(Path().absolute()).replace('\\', '/')
    else:
        return os.path.join(Path().absolute(), relative_path).replace('\\', '/')


def resource_path(relative_path):
    """
    Get absolute path to resource, works for dev and for PyInstaller

    Credit: https://stackoverflow.com/questions/7674790/bundling-data-files-with-pyinstaller-onefile/13790741#13790741
    """
    # try:
    #     # PyInstaller creates a temp folder and stores path in _MEIPASS
    #     path = sys._MEIPASS
    # except Exception:
    #     path = os.path.abspath(".")
    path = os.path.abspath(".")
    return os.path.join(path, relative_path).replace('\\', '/')


def abs_to_rel(p):
    # Convert to relative path, if possible
    rel_path = p.replace(absolute_path(), "")

    # Store Path
    if rel_path != p:
        return rel_path[1:]
    else:
        return p


def rel_to_abs(p):
    if not os.path.isabs(p):
        return absolute_path(p)
    else:
        return p
