import os
import shutil
import sys
from pathlib import Path


# Where the macOS app keeps the files it reads and writes, see install_mac_app_data()
MAC_APP_DATA_DIR = os.path.expanduser("~/Library/Application Support/AutoSplit64++")


def install_mac_app_data():
    """
    A macOS .app can be installed anywhere and must not modify itself. Copy the files bundled
    in it to MAC_APP_DATA_DIR, next to the user's settings, and run from there.
    """
    def copy_if_changed(src, dst):
        if not os.path.exists(dst) or os.path.getsize(src) != os.path.getsize(dst) or os.path.getmtime(src) != os.path.getmtime(dst):
            shutil.copy2(src, dst)

    def copy_if_missing(src, dst):
        if not os.path.exists(dst):
            shutil.copy2(src, dst)

    bundle = sys._MEIPASS
    os.makedirs(MAC_APP_DATA_DIR, exist_ok=True)
    # Updated with the app
    shutil.copytree(os.path.join(bundle, "resources"), os.path.join(MAC_APP_DATA_DIR, "resources"), dirs_exist_ok=True, copy_function=copy_if_changed)
    copy_if_changed(os.path.join(bundle, "defaults.ini"), os.path.join(MAC_APP_DATA_DIR, "defaults.ini"))
    # Edited or generated by the user, so existing files are kept
    for name in ("routes", "templates"):
        shutil.copytree(os.path.join(bundle, name), os.path.join(MAC_APP_DATA_DIR, name), dirs_exist_ok=True, copy_function=copy_if_missing)

    os.chdir(MAC_APP_DATA_DIR)


def base_path(relative_path=None):
    # Run from source, the app is started in the repository's root
    directory = os.getcwd()
    if getattr(sys, "frozen", False):
        directory = MAC_APP_DATA_DIR if sys.platform == "darwin" else os.path.dirname(sys.argv[0])

    if not relative_path:
        return directory
    else:
        return os.path.join(directory, relative_path).replace('\\', '/')


def absolute_path(relative_path=None):
    if not relative_path:
        return str(Path().absolute()).replace('\\', '/')
    else:
        return os.path.join(Path().absolute(), relative_path).replace('\\', '/')


def resource_path(relative_path):
    """
    Get absolute path to resource, works for dev and for PyInstaller

    Credit: https://stackoverflow.com/questions/7674790/bundling-data-files-with-pyinstaller-onefile/13790741#13790741
    """
    path = os.path.abspath(".")
    return os.path.join(path, relative_path).replace('\\', '/')


def abs_to_rel(p):
    """ p relative to the working directory if it's inside it, otherwise unchanged """
    try:
        return Path(p).relative_to(Path.cwd()).as_posix()
    except ValueError:
        return p


def rel_to_abs(p):
    if not os.path.isabs(p):
        return absolute_path(p)
    else:
        return p
